// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.bubukj.proto;

public interface AskbannerListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AskbannerList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string url = 2;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
