// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.bubukj.proto;

public interface CompanyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CompanyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 type = 2;</code>
   */
  int getType();

  /**
   * <code>string headimg = 3;</code>
   */
  java.lang.String getHeadimg();
  /**
   * <code>string headimg = 3;</code>
   */
  com.google.protobuf.ByteString
      getHeadimgBytes();

  /**
   * <code>string service = 4;</code>
   */
  java.lang.String getService();
  /**
   * <code>string service = 4;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string realName = 5;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string realName = 5;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();

  /**
   * <code>string companyName = 6;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 6;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string address = 7;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 7;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string count = 8;</code>
   */
  java.lang.String getCount();
  /**
   * <code>string count = 8;</code>
   */
  com.google.protobuf.ByteString
      getCountBytes();
}
