// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.bubukj.proto;

public final class HomeOuterClass {
  private HomeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CompanyList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CompanyList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BannerList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BannerList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskbannerList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskbannerList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SkillList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SkillList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HomeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HomeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Home_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Home_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Home_Wisdom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Home_Wisdom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Home_TaskHall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Home_TaskHall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhome.proto\"\220\001\n\013CompanyList\022\n\n\002id\030\001 \001(\t" +
      "\022\014\n\004type\030\002 \001(\005\022\017\n\007headimg\030\003 \001(\t\022\017\n\007servi" +
      "ce\030\004 \001(\t\022\020\n\010realName\030\005 \001(\t\022\023\n\013companyNam" +
      "e\030\006 \001(\t\022\017\n\007address\030\007 \001(\t\022\r\n\005count\030\010 \001(\t\"" +
      "%\n\nBannerList\022\n\n\002id\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\"(" +
      "\n\rAskbannerList\022\n\n\002id\030\001 \001(\t\022\013\n\003url\030\002 \001(\t" +
      "\"\271\001\n\010TaskList\022\n\n\002id\030\001 \001(\t\022\r\n\005title\030\002 \001(\t" +
      "\022\020\n\010priceMin\030\003 \001(\t\022\020\n\010priceMax\030\004 \001(\t\022\021\n\t" +
      "lifecycle\030\005 \001(\t\022\020\n\010workType\030\006 \001(\t\022\023\n\013use" +
      "rHeadimg\030\007 \001(\t\022\020\n\010userName\030\010 \001(\t\022\023\n\013comp",
      "anyName\030\t \001(\t\022\r\n\005count\030\n \001(\t\"3\n\tSkillLis" +
      "t\022\n\n\002id\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\013\n\003img\030\003 \001(" +
      "\t\"\031\n\013HomeRequest\022\n\n\002id\030\001 \001(\t\"\226\002\n\004Home\022\034\n" +
      "\007banList\030\003 \003(\0132\013.BannerList\022\"\n\naskbanLis" +
      "t\030\004 \003(\0132\016.AskbannerList\022\033\n\010taskList\030\005 \003(" +
      "\0132\t.TaskList\022!\n\013companyList\030\006 \003(\0132\014.Comp" +
      "anyList\032D\n\006Wisdom\022\033\n\007skiList\030\001 \001(\0132\n.Ski" +
      "llList\022\035\n\007comList\030\002 \003(\0132\014.CompanyList\032F\n" +
      "\010TaskHall\022\033\n\007skiList\030\001 \001(\0132\n.SkillList\022\035" +
      "\n\007comList\030\002 \003(\0132\014.CompanyList2.\n\nHuibaoH",
      "ome\022 \n\007GetHome\022\014.HomeRequest\032\005.Home\"\000B\024\n" +
      "\020com.bubukj.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CompanyList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CompanyList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CompanyList_descriptor,
        new java.lang.String[] { "Id", "Type", "Headimg", "Service", "RealName", "CompanyName", "Address", "Count", });
    internal_static_BannerList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BannerList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BannerList_descriptor,
        new java.lang.String[] { "Id", "Url", });
    internal_static_AskbannerList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AskbannerList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskbannerList_descriptor,
        new java.lang.String[] { "Id", "Url", });
    internal_static_TaskList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskList_descriptor,
        new java.lang.String[] { "Id", "Title", "PriceMin", "PriceMax", "Lifecycle", "WorkType", "UserHeadimg", "UserName", "CompanyName", "Count", });
    internal_static_SkillList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SkillList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SkillList_descriptor,
        new java.lang.String[] { "Id", "Title", "Img", });
    internal_static_HomeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_HomeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HomeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Home_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Home_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Home_descriptor,
        new java.lang.String[] { "BanList", "AskbanList", "TaskList", "CompanyList", });
    internal_static_Home_Wisdom_descriptor =
      internal_static_Home_descriptor.getNestedTypes().get(0);
    internal_static_Home_Wisdom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Home_Wisdom_descriptor,
        new java.lang.String[] { "SkiList", "ComList", });
    internal_static_Home_TaskHall_descriptor =
      internal_static_Home_descriptor.getNestedTypes().get(1);
    internal_static_Home_TaskHall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Home_TaskHall_descriptor,
        new java.lang.String[] { "SkiList", "ComList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
