// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.bubukj.proto;

public interface HomeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Home)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .BannerList banList = 3;</code>
   */
  java.util.List<com.bubukj.proto.BannerList> 
      getBanListList();
  /**
   * <code>repeated .BannerList banList = 3;</code>
   */
  com.bubukj.proto.BannerList getBanList(int index);
  /**
   * <code>repeated .BannerList banList = 3;</code>
   */
  int getBanListCount();
  /**
   * <code>repeated .BannerList banList = 3;</code>
   */
  java.util.List<? extends com.bubukj.proto.BannerListOrBuilder> 
      getBanListOrBuilderList();
  /**
   * <code>repeated .BannerList banList = 3;</code>
   */
  com.bubukj.proto.BannerListOrBuilder getBanListOrBuilder(
      int index);

  /**
   * <code>repeated .AskbannerList askbanList = 4;</code>
   */
  java.util.List<com.bubukj.proto.AskbannerList> 
      getAskbanListList();
  /**
   * <code>repeated .AskbannerList askbanList = 4;</code>
   */
  com.bubukj.proto.AskbannerList getAskbanList(int index);
  /**
   * <code>repeated .AskbannerList askbanList = 4;</code>
   */
  int getAskbanListCount();
  /**
   * <code>repeated .AskbannerList askbanList = 4;</code>
   */
  java.util.List<? extends com.bubukj.proto.AskbannerListOrBuilder> 
      getAskbanListOrBuilderList();
  /**
   * <code>repeated .AskbannerList askbanList = 4;</code>
   */
  com.bubukj.proto.AskbannerListOrBuilder getAskbanListOrBuilder(
      int index);

  /**
   * <code>repeated .TaskList taskList = 5;</code>
   */
  java.util.List<com.bubukj.proto.TaskList> 
      getTaskListList();
  /**
   * <code>repeated .TaskList taskList = 5;</code>
   */
  com.bubukj.proto.TaskList getTaskList(int index);
  /**
   * <code>repeated .TaskList taskList = 5;</code>
   */
  int getTaskListCount();
  /**
   * <code>repeated .TaskList taskList = 5;</code>
   */
  java.util.List<? extends com.bubukj.proto.TaskListOrBuilder> 
      getTaskListOrBuilderList();
  /**
   * <code>repeated .TaskList taskList = 5;</code>
   */
  com.bubukj.proto.TaskListOrBuilder getTaskListOrBuilder(
      int index);

  /**
   * <code>repeated .CompanyList companyList = 6;</code>
   */
  java.util.List<com.bubukj.proto.CompanyList> 
      getCompanyListList();
  /**
   * <code>repeated .CompanyList companyList = 6;</code>
   */
  com.bubukj.proto.CompanyList getCompanyList(int index);
  /**
   * <code>repeated .CompanyList companyList = 6;</code>
   */
  int getCompanyListCount();
  /**
   * <code>repeated .CompanyList companyList = 6;</code>
   */
  java.util.List<? extends com.bubukj.proto.CompanyListOrBuilder> 
      getCompanyListOrBuilderList();
  /**
   * <code>repeated .CompanyList companyList = 6;</code>
   */
  com.bubukj.proto.CompanyListOrBuilder getCompanyListOrBuilder(
      int index);
}
