// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.bubukj.proto;

public interface SkillListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SkillList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string img = 3;</code>
   */
  java.lang.String getImg();
  /**
   * <code>string img = 3;</code>
   */
  com.google.protobuf.ByteString
      getImgBytes();
}
