// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.bubukj.proto;

/**
 * Protobuf type {@code TaskList}
 */
public  final class TaskList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TaskList)
    TaskListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskList.newBuilder() to construct.
  private TaskList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskList() {
    id_ = "";
    title_ = "";
    priceMin_ = "";
    priceMax_ = "";
    lifecycle_ = "";
    workType_ = "";
    userHeadimg_ = "";
    userName_ = "";
    companyName_ = "";
    count_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            priceMin_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            priceMax_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            lifecycle_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            workType_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            userHeadimg_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            companyName_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            count_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bubukj.proto.HomeOuterClass.internal_static_TaskList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bubukj.proto.HomeOuterClass.internal_static_TaskList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bubukj.proto.TaskList.class, com.bubukj.proto.TaskList.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICEMIN_FIELD_NUMBER = 3;
  private volatile java.lang.Object priceMin_;
  /**
   * <code>string priceMin = 3;</code>
   */
  public java.lang.String getPriceMin() {
    java.lang.Object ref = priceMin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      priceMin_ = s;
      return s;
    }
  }
  /**
   * <code>string priceMin = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPriceMinBytes() {
    java.lang.Object ref = priceMin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      priceMin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICEMAX_FIELD_NUMBER = 4;
  private volatile java.lang.Object priceMax_;
  /**
   * <code>string priceMax = 4;</code>
   */
  public java.lang.String getPriceMax() {
    java.lang.Object ref = priceMax_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      priceMax_ = s;
      return s;
    }
  }
  /**
   * <code>string priceMax = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPriceMaxBytes() {
    java.lang.Object ref = priceMax_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      priceMax_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIFECYCLE_FIELD_NUMBER = 5;
  private volatile java.lang.Object lifecycle_;
  /**
   * <code>string lifecycle = 5;</code>
   */
  public java.lang.String getLifecycle() {
    java.lang.Object ref = lifecycle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lifecycle_ = s;
      return s;
    }
  }
  /**
   * <code>string lifecycle = 5;</code>
   */
  public com.google.protobuf.ByteString
      getLifecycleBytes() {
    java.lang.Object ref = lifecycle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lifecycle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKTYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object workType_;
  /**
   * <code>string workType = 6;</code>
   */
  public java.lang.String getWorkType() {
    java.lang.Object ref = workType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workType_ = s;
      return s;
    }
  }
  /**
   * <code>string workType = 6;</code>
   */
  public com.google.protobuf.ByteString
      getWorkTypeBytes() {
    java.lang.Object ref = workType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERHEADIMG_FIELD_NUMBER = 7;
  private volatile java.lang.Object userHeadimg_;
  /**
   * <code>string userHeadimg = 7;</code>
   */
  public java.lang.String getUserHeadimg() {
    java.lang.Object ref = userHeadimg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userHeadimg_ = s;
      return s;
    }
  }
  /**
   * <code>string userHeadimg = 7;</code>
   */
  public com.google.protobuf.ByteString
      getUserHeadimgBytes() {
    java.lang.Object ref = userHeadimg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userHeadimg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object userName_;
  /**
   * <code>string userName = 8;</code>
   */
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string userName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANYNAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object companyName_;
  /**
   * <code>string companyName = 9;</code>
   */
  public java.lang.String getCompanyName() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyName_ = s;
      return s;
    }
  }
  /**
   * <code>string companyName = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCompanyNameBytes() {
    java.lang.Object ref = companyName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNT_FIELD_NUMBER = 10;
  private volatile java.lang.Object count_;
  /**
   * <code>string count = 10;</code>
   */
  public java.lang.String getCount() {
    java.lang.Object ref = count_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      count_ = s;
      return s;
    }
  }
  /**
   * <code>string count = 10;</code>
   */
  public com.google.protobuf.ByteString
      getCountBytes() {
    java.lang.Object ref = count_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      count_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!getPriceMinBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, priceMin_);
    }
    if (!getPriceMaxBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, priceMax_);
    }
    if (!getLifecycleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lifecycle_);
    }
    if (!getWorkTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, workType_);
    }
    if (!getUserHeadimgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userHeadimg_);
    }
    if (!getUserNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userName_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, companyName_);
    }
    if (!getCountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, count_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!getPriceMinBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, priceMin_);
    }
    if (!getPriceMaxBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, priceMax_);
    }
    if (!getLifecycleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lifecycle_);
    }
    if (!getWorkTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, workType_);
    }
    if (!getUserHeadimgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userHeadimg_);
    }
    if (!getUserNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userName_);
    }
    if (!getCompanyNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, companyName_);
    }
    if (!getCountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, count_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bubukj.proto.TaskList)) {
      return super.equals(obj);
    }
    com.bubukj.proto.TaskList other = (com.bubukj.proto.TaskList) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getPriceMin()
        .equals(other.getPriceMin());
    result = result && getPriceMax()
        .equals(other.getPriceMax());
    result = result && getLifecycle()
        .equals(other.getLifecycle());
    result = result && getWorkType()
        .equals(other.getWorkType());
    result = result && getUserHeadimg()
        .equals(other.getUserHeadimg());
    result = result && getUserName()
        .equals(other.getUserName());
    result = result && getCompanyName()
        .equals(other.getCompanyName());
    result = result && getCount()
        .equals(other.getCount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + PRICEMIN_FIELD_NUMBER;
    hash = (53 * hash) + getPriceMin().hashCode();
    hash = (37 * hash) + PRICEMAX_FIELD_NUMBER;
    hash = (53 * hash) + getPriceMax().hashCode();
    hash = (37 * hash) + LIFECYCLE_FIELD_NUMBER;
    hash = (53 * hash) + getLifecycle().hashCode();
    hash = (37 * hash) + WORKTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getWorkType().hashCode();
    hash = (37 * hash) + USERHEADIMG_FIELD_NUMBER;
    hash = (53 * hash) + getUserHeadimg().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + COMPANYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyName().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bubukj.proto.TaskList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bubukj.proto.TaskList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bubukj.proto.TaskList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bubukj.proto.TaskList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bubukj.proto.TaskList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bubukj.proto.TaskList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bubukj.proto.TaskList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bubukj.proto.TaskList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bubukj.proto.TaskList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bubukj.proto.TaskList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bubukj.proto.TaskList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bubukj.proto.TaskList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bubukj.proto.TaskList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TaskList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TaskList)
      com.bubukj.proto.TaskListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bubukj.proto.HomeOuterClass.internal_static_TaskList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bubukj.proto.HomeOuterClass.internal_static_TaskList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bubukj.proto.TaskList.class, com.bubukj.proto.TaskList.Builder.class);
    }

    // Construct using com.bubukj.proto.TaskList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      title_ = "";

      priceMin_ = "";

      priceMax_ = "";

      lifecycle_ = "";

      workType_ = "";

      userHeadimg_ = "";

      userName_ = "";

      companyName_ = "";

      count_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bubukj.proto.HomeOuterClass.internal_static_TaskList_descriptor;
    }

    public com.bubukj.proto.TaskList getDefaultInstanceForType() {
      return com.bubukj.proto.TaskList.getDefaultInstance();
    }

    public com.bubukj.proto.TaskList build() {
      com.bubukj.proto.TaskList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bubukj.proto.TaskList buildPartial() {
      com.bubukj.proto.TaskList result = new com.bubukj.proto.TaskList(this);
      result.id_ = id_;
      result.title_ = title_;
      result.priceMin_ = priceMin_;
      result.priceMax_ = priceMax_;
      result.lifecycle_ = lifecycle_;
      result.workType_ = workType_;
      result.userHeadimg_ = userHeadimg_;
      result.userName_ = userName_;
      result.companyName_ = companyName_;
      result.count_ = count_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bubukj.proto.TaskList) {
        return mergeFrom((com.bubukj.proto.TaskList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bubukj.proto.TaskList other) {
      if (other == com.bubukj.proto.TaskList.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getPriceMin().isEmpty()) {
        priceMin_ = other.priceMin_;
        onChanged();
      }
      if (!other.getPriceMax().isEmpty()) {
        priceMax_ = other.priceMax_;
        onChanged();
      }
      if (!other.getLifecycle().isEmpty()) {
        lifecycle_ = other.lifecycle_;
        onChanged();
      }
      if (!other.getWorkType().isEmpty()) {
        workType_ = other.workType_;
        onChanged();
      }
      if (!other.getUserHeadimg().isEmpty()) {
        userHeadimg_ = other.userHeadimg_;
        onChanged();
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getCompanyName().isEmpty()) {
        companyName_ = other.companyName_;
        onChanged();
      }
      if (!other.getCount().isEmpty()) {
        count_ = other.count_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bubukj.proto.TaskList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bubukj.proto.TaskList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object priceMin_ = "";
    /**
     * <code>string priceMin = 3;</code>
     */
    public java.lang.String getPriceMin() {
      java.lang.Object ref = priceMin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceMin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string priceMin = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPriceMinBytes() {
      java.lang.Object ref = priceMin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceMin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string priceMin = 3;</code>
     */
    public Builder setPriceMin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      priceMin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string priceMin = 3;</code>
     */
    public Builder clearPriceMin() {
      
      priceMin_ = getDefaultInstance().getPriceMin();
      onChanged();
      return this;
    }
    /**
     * <code>string priceMin = 3;</code>
     */
    public Builder setPriceMinBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      priceMin_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object priceMax_ = "";
    /**
     * <code>string priceMax = 4;</code>
     */
    public java.lang.String getPriceMax() {
      java.lang.Object ref = priceMax_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceMax_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string priceMax = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPriceMaxBytes() {
      java.lang.Object ref = priceMax_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceMax_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string priceMax = 4;</code>
     */
    public Builder setPriceMax(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      priceMax_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string priceMax = 4;</code>
     */
    public Builder clearPriceMax() {
      
      priceMax_ = getDefaultInstance().getPriceMax();
      onChanged();
      return this;
    }
    /**
     * <code>string priceMax = 4;</code>
     */
    public Builder setPriceMaxBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      priceMax_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lifecycle_ = "";
    /**
     * <code>string lifecycle = 5;</code>
     */
    public java.lang.String getLifecycle() {
      java.lang.Object ref = lifecycle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lifecycle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lifecycle = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLifecycleBytes() {
      java.lang.Object ref = lifecycle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lifecycle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lifecycle = 5;</code>
     */
    public Builder setLifecycle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lifecycle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lifecycle = 5;</code>
     */
    public Builder clearLifecycle() {
      
      lifecycle_ = getDefaultInstance().getLifecycle();
      onChanged();
      return this;
    }
    /**
     * <code>string lifecycle = 5;</code>
     */
    public Builder setLifecycleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lifecycle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object workType_ = "";
    /**
     * <code>string workType = 6;</code>
     */
    public java.lang.String getWorkType() {
      java.lang.Object ref = workType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string workType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWorkTypeBytes() {
      java.lang.Object ref = workType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string workType = 6;</code>
     */
    public Builder setWorkType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string workType = 6;</code>
     */
    public Builder clearWorkType() {
      
      workType_ = getDefaultInstance().getWorkType();
      onChanged();
      return this;
    }
    /**
     * <code>string workType = 6;</code>
     */
    public Builder setWorkTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userHeadimg_ = "";
    /**
     * <code>string userHeadimg = 7;</code>
     */
    public java.lang.String getUserHeadimg() {
      java.lang.Object ref = userHeadimg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userHeadimg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userHeadimg = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserHeadimgBytes() {
      java.lang.Object ref = userHeadimg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userHeadimg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userHeadimg = 7;</code>
     */
    public Builder setUserHeadimg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userHeadimg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userHeadimg = 7;</code>
     */
    public Builder clearUserHeadimg() {
      
      userHeadimg_ = getDefaultInstance().getUserHeadimg();
      onChanged();
      return this;
    }
    /**
     * <code>string userHeadimg = 7;</code>
     */
    public Builder setUserHeadimgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userHeadimg_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string userName = 8;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userName = 8;</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 8;</code>
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string userName = 8;</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyName_ = "";
    /**
     * <code>string companyName = 9;</code>
     */
    public java.lang.String getCompanyName() {
      java.lang.Object ref = companyName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string companyName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyNameBytes() {
      java.lang.Object ref = companyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string companyName = 9;</code>
     */
    public Builder setCompanyName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string companyName = 9;</code>
     */
    public Builder clearCompanyName() {
      
      companyName_ = getDefaultInstance().getCompanyName();
      onChanged();
      return this;
    }
    /**
     * <code>string companyName = 9;</code>
     */
    public Builder setCompanyNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object count_ = "";
    /**
     * <code>string count = 10;</code>
     */
    public java.lang.String getCount() {
      java.lang.Object ref = count_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        count_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string count = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCountBytes() {
      java.lang.Object ref = count_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        count_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string count = 10;</code>
     */
    public Builder setCount(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string count = 10;</code>
     */
    public Builder clearCount() {
      
      count_ = getDefaultInstance().getCount();
      onChanged();
      return this;
    }
    /**
     * <code>string count = 10;</code>
     */
    public Builder setCountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      count_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TaskList)
  }

  // @@protoc_insertion_point(class_scope:TaskList)
  private static final com.bubukj.proto.TaskList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bubukj.proto.TaskList();
  }

  public static com.bubukj.proto.TaskList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskList>
      PARSER = new com.google.protobuf.AbstractParser<TaskList>() {
    public TaskList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskList> getParserForType() {
    return PARSER;
  }

  public com.bubukj.proto.TaskList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

