// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home.proto

package com.bubukj.proto;

public interface TaskListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TaskList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string priceMin = 3;</code>
   */
  java.lang.String getPriceMin();
  /**
   * <code>string priceMin = 3;</code>
   */
  com.google.protobuf.ByteString
      getPriceMinBytes();

  /**
   * <code>string priceMax = 4;</code>
   */
  java.lang.String getPriceMax();
  /**
   * <code>string priceMax = 4;</code>
   */
  com.google.protobuf.ByteString
      getPriceMaxBytes();

  /**
   * <code>string lifecycle = 5;</code>
   */
  java.lang.String getLifecycle();
  /**
   * <code>string lifecycle = 5;</code>
   */
  com.google.protobuf.ByteString
      getLifecycleBytes();

  /**
   * <code>string workType = 6;</code>
   */
  java.lang.String getWorkType();
  /**
   * <code>string workType = 6;</code>
   */
  com.google.protobuf.ByteString
      getWorkTypeBytes();

  /**
   * <code>string userHeadimg = 7;</code>
   */
  java.lang.String getUserHeadimg();
  /**
   * <code>string userHeadimg = 7;</code>
   */
  com.google.protobuf.ByteString
      getUserHeadimgBytes();

  /**
   * <code>string userName = 8;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 8;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string companyName = 9;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 9;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string count = 10;</code>
   */
  java.lang.String getCount();
  /**
   * <code>string count = 10;</code>
   */
  com.google.protobuf.ByteString
      getCountBytes();
}
